DROP TABLE IF EXISTS comments, bookings, items, users, requests CASCADE;


CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     user_name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     item_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     owner_id BIGINT REFERENCES users (user_id),
                                     item_name VARCHAR(255) NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     is_available BOOLEAN NOT NULL,
                                     request_id int,
                                     CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                        booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id int REFERENCES items (item_id) ON delete CASCADE,
                                        booker_id BIGINT REFERENCES users (user_id),
                                        status VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS comments (
                                        comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text VARCHAR(512) NOT NULL,
                                        item_id int REFERENCES items (item_id) ON delete CASCADE,
                                        author_id BIGINT REFERENCES users (user_id),
                                        created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

create TABLE IF NOT EXISTS requests (
                                        request_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        requester_id int REFERENCES users (user_id) ON delete CASCADE,
                                        description varchar(300) NOT NULL,
                                        created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT request_id PRIMARY KEY (request_id)
);




